### ISSUE TITLE
Manque le sql

### ISSUE THREAD

**Issue by jpom57** [Clan-RmG-Royal-Multi-Gamers/Ex_extended_Double_Jobs_No_Essential#1]
Bonjours il manque juste le fichier sql modifié
bonne journee

**Comment by ineokb** [comment]
ça prend deux secondes à le faire regarde juste le job2 job2_grade et tu vois ce qu'il faut add, merci pour la release en tout cas ! 
En gros job2 par default : unemployed2
Et job2_grade après dans users

**Comment by Destructor** [comment]
C'est ajouté

**Comment by jpom57** [comment]
Chez moi le script ne fonctionne pas j ai une erreur et le jeux charge sans fin
[es_extended] [WARNING] Ignoring job "unemployed2" due to no job grades found
Alors que j ai bien mis dans la base slq
